CREATE TRIGGER t_auto_update_epoch_on_routes BEFORE UPDATE ON routes FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_users BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_blocks BEFORE UPDATE ON blocks FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_dicts BEFORE UPDATE ON dicts FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_groups BEFORE UPDATE ON groups FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_user_groups BEFORE UPDATE ON user_groups FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_extn_groups BEFORE UPDATE ON extn_groups FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_gateways BEFORE UPDATE ON gateways FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_params BEFORE UPDATE ON params FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_sip_profiles BEFORE UPDATE ON sip_profiles FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_media_files BEFORE UPDATE ON media_files FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_conference_rooms BEFORE UPDATE ON conference_rooms FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_conference_members BEFORE UPDATE ON conference_members FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_devices BEFORE UPDATE ON devices FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_user_devices BEFORE UPDATE ON user_devices FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_fifos BEFORE UPDATE ON fifos FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_fifo_members BEFORE UPDATE ON fifo_members FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_mcasts BEFORE UPDATE ON mcasts FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_mfile_mcasts BEFORE UPDATE ON mfile_mcasts FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_permissions BEFORE UPDATE ON permissions FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_group_permission BEFORE UPDATE ON group_permission FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_conference_profiles BEFORE UPDATE ON conference_profiles FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_ivr_menus BEFORE UPDATE ON ivr_menus FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_acls BEFORE UPDATE ON acls FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_acl_nodes BEFORE UPDATE ON acl_nodes FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_ivr_actions BEFORE UPDATE ON ivr_actions FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_tickets BEFORE UPDATE ON tickets FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_ticket_comments BEFORE UPDATE ON ticket_comments FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_ticket_comment_media BEFORE UPDATE ON ticket_comment_media FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_wechat_users BEFORE UPDATE ON wechat_users FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();
CREATE TRIGGER t_auto_update_epoch_on_wechat_upload BEFORE UPDATE ON wechat_upload FOR EACH ROW EXECUTE PROCEDURE auto_update_updated_epoch();

ALTER TABLE routes ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE users ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE blocks ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE dicts ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE groups ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_groups ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE extn_groups ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE gateways ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE params ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE sip_profiles ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE media_files ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_rooms ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_members ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE devices ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_devices ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifos ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifo_members ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE mcasts ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE mfile_mcasts ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE permissions ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE group_permissions ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_profiles ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_menus ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE acls ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE acl_nodes ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_actions ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE tickets ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comments ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comment_media ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_users ALTER created_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_upload ALTER created_epoch TYPE TIMESTAMP(0);

ALTER TABLE routes ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE users ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE blocks ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE dicts ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE groups ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_groups ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE extn_groups ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE gateways ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE params ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE sip_profiles ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE media_files ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_rooms ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_members ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE devices ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_devices ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifos ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifo_members ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE mcasts ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE mfile_mcasts ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE permissions ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE group_permissions ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_profiles ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_menus ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE acls ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE acl_nodes ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_actions ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE tickets ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comments ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comment_media ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_users ALTER updated_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_upload ALTER updated_epoch TYPE TIMESTAMP(0);

ALTER TABLE routes ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE users ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE blocks ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE dicts ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE groups ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_groups ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE extn_groups ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE gateways ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE params ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE sip_profiles ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE media_files ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_rooms ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_members ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE devices ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE user_devices ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifos ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE fifo_members ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE mcasts ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE mfile_mcasts ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE permissions ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE group_permissions ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE conference_profiles ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_menus ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE acls ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE acl_nodes ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE ivr_actions ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE tickets ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comments ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE ticket_comment_media ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_users ALTER deleted_epoch TYPE TIMESTAMP(0);
ALTER TABLE wechat_upload ALTER deleted_epoch TYPE TIMESTAMP(0);


ALTER TABLE tickets ALTER completed_epoch TYPE TIMESTAMP(0);
