all:
	npm run build

githash:
	npm run githash

watch:
	npm run build:watch

wewatch:
	webpack -w --config webpack.wechat.js

webuild:
	webpack -p --config webpack.wechat.js

release:
	npm run release

livereload:
	npm run livereload
